- name: Add an apt key by id for erlang
  apt_key:
    keyserver: "{{ erlang_apt_repo_gpgkey_server }}"
    id: "{{ erlang_apt_repo_gpgkey_id }}"
    state: present
  become: true

- name: Add apt repository for erlang
  apt_repository:
    repo: "{{ erlang_apt_repo_url }}"
    filename: rabbitmq_erlang
    update_cache: no
  become: true

- name: Set package erlang preference
  copy:
    dest: /etc/apt/preferences.d/erlang
    content: |
      Package: erlang*
      Pin: release o=Bintray
      Pin-Priority: 1000
  become: true

- name: Pin RabbitMQ version
  copy:
    dest: /etc/apt/preferences.d/rabbitmq
    content: |
      Package: rabbitmq-server
      Pin: version {{ rabbitmq_version }}
      Pin-Priority: 1002
  become: true
  when: rabbitmq_pin_version | bool == True

- name: Add an apt key by id for rabbitmq
  apt_key:
    keyserver: "{{ rabbitmq_apt_repo_gpgkey_server }}"
    id: "{{ rabbitmq_apt_repo_gpgkey_id }}"
    state: present
  become: true

- name: Add apt repository for rabbitmq
  apt_repository:
    repo: "{{ rabbitmq_apt_repo_url }}"
    filename: rabbitmq_main
    update_cache: yes
  become: true

- name: Install RabbitMQ
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    update_cache: yes
    state: present
    # Prevent Rabbit from starting immediately after installation before we could apply custom config (including clustering)
    policy_rc_d: 101 # 101 means "action forbidden by policy"
  notify: restart rabbitmq-server
  become: true

- meta: flush_handlers
