---
- name: include rabbitmq installation tasks
  include_tasks: install-{{ ansible_os_family }}.yml

- name: enable offline plugins
  include_tasks: plugins.yml
  vars:
    _rabbitmq_plugins: "{{ rabbitmq_offline_plugins }}"

- include_tasks: configure.yml

- name: flush handlers
  meta: flush_handlers

- name: ensure rabbitmq-server is started
  service:
    name: rabbitmq-server
    enabled: true
    state: started
  become: true

- name: enable online plugins
  include_tasks: plugins.yml
  vars:
    _rabbitmq_plugins: "{{ rabbitmq_online_plugins }}"

- include_tasks: cluster.yml

- include_tasks: vhosts.yml

- include_tasks: users.yml

- include_tasks: policies.yml
