---
- name: include rabbitmq installation tasks
  include: install-{{ ansible_os_family }}.yml

- name: enable offline plugins
  include: plugins.yml
  vars:
    _rabbitmq_plugins: "{{ rabbitmq_offline_plugins }}"

- include: configure.yml

- name: flush handlers
  meta: flush_handlers

- name: ensure rabbitmq-server is started
  service:
    name: rabbitmq-server
    enabled: true
    state: started
  become: true

- name: enable online plugins
  include: plugins.yml
  vars:
    _rabbitmq_plugins: "{{ rabbitmq_online_plugins }}"

- include: cluster.yml

- include: vhosts.yml

- include: users.yml

- include: policies.yml
