---
- name: remove rabbitmq users
  rabbitmq_user:
    user: "{{ item.user | default(item) }}"
    node: "{{ item.node | default(ansible_env.RABBITMQ_NODENAME) | default('rabbit') }}"
    state: absent
  with_items: "{{ rabbitmq_users_absent }}"
  run_once: "{{ rabbitmq_cluster }}"
  become: true

- name: add rabbitmq users
  rabbitmq_user:
    user: "{{ item.user }}"
    node: "{{ item.node | default(ansible_env.RABBITMQ_NODENAME) | default('rabbit') }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost | default('/') }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    tags: "{{ item.tags | default('') }}"
  with_items: "{{ rabbitmq_users }}"
  run_once: "{{ rabbitmq_cluster }}"
  no_log: true
  become: true
